# Generated by Django 4.2.7 on 2024-07-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(max_length=10, unique=True)),
                ('nama_fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='programstudi',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='administrator.fakultas'),
        ),
    ]
